imports:
    - { resource: services.yaml }
    - { resource: system.yml }

pimcore:
    chromium:
        uri: '%env(PIMCORE_TEST_CHROMIUM_DNS)%'

    gotenberg:
        base_url: '%env(PIMCORE_TEST_GOTENBERG_DNS)%'

    email:
        sender:
            name: pimcore
            email: pimcore@example.com
        return:
            name: pimcore
            email: pimcore@example.com
    config_location:
        image_thumbnails:
            write_target:
                type: 'settings-store'
        video_thumbnails:
            write_target:
                type: 'settings-store'
        document_types:
            write_target:
                type: 'settings-store'
        predefined_properties:
            write_target:
                type: 'settings-store'
        predefined_asset_metadata:
            write_target:
                type: 'settings-store'
        perspectives:
            write_target:
                type: 'settings-store'
        custom_views:
            write_target:
                type: 'settings-store'
        object_custom_layouts:
            write_target:
                type: 'settings-store'
        system_settings:
            write_target:
                type: 'settings-store'
            read_target:
                type: 'settings-store'

    documents:
        type_definitions:
            map:
                printpage:
                    class: Pimcore\Bundle\WebToPrintBundle\Model\Document\Printpage
                    children_supported: false
                    direct_route: true
                    predefined_document_types: true
                printcontainer:
                    class: Pimcore\Bundle\WebToPrintBundle\Model\Document\Printcontainer
                    only_printable_childrens: true
                    direct_route: true
                    predefined_document_types: true

pimcore_admin:
    config_location:
        admin_system_settings:
            write_target:
                type: 'settings-store'
            read_target:
                type: 'settings-store'


